### Indexing with Boolean Arrays Numpy

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,100,20).reshape(4,5)
print(arr)

[[30 99 72 66 56]
 [75 41 52 55 53]
 [12 18 28 35 50]
 [17 71 91  8 93]]


In [13]:
print(arr>50) #Boolean Array

#Indexing using boolean arrays (filtering)
print(arr[arr>50]) # Prints all the numbers greater than 50
print(arr[arr>50].size) # 11 elements are greater than 50

# Using multiple conditions
print(arr[(arr>50) & (arr%2!=0)]) # using bitwise & on boolean values

[[False  True  True  True  True]
 [ True False  True  True  True]
 [False False False False False]
 [False  True  True False  True]]
[99 72 66 56 75 52 55 53 71 91 93]
11
[99 75 55 53 71 91 93]


In [14]:
# Setting numbers to 0 based on some condition
arr[(arr>50) & (arr%2!=0)] =0
print(arr)

[[30  0 72 66 56]
 [ 0 41 52  0  0]
 [12 18 28 35 50]
 [17  0  0  8  0]]
