### NumPy Broadcasting

In [1]:
import numpy as np

In [3]:
#Scenario 1
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
# Scenario 2
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [7]:
a3+a4 # even though the shape is not same but numpy stills adds them
# One row gets added to all three rows

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

**Broadcasting** 


The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmatic operations. Arithmatic operations on arrays are usually done on corresponding elements. If arrays are exactly the same shape, then these operations are smoothly performed.

If the dimentions of two arrays are dissimilar, element-to-element operations are not possible. However operations on arrays of non similar shapes is still possible in numpy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shape.

**Rules of Broadcasting**

In [17]:
# For Two arrays with shapes (x,y) and (a,b)
# If x=a and y=b, Operation will take place normally- Scenario 1
# If (x|y|a|b) = 1 and corresponding axis are same then also operation will take place by broadcasting - Scenatio 2

# Scenario 3 same as 2
a5 = np.arange(3).reshape(3,1)
a6 = np.arange(12).reshape(3,4)

print(a5, "\t", "\n\n", a6, "\n")

print(a5+a6)

[[0]
 [1]
 [2]] 	 

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [18]:
#If (x|y|a|b) = 1 and corresponding axis are not same then operation can not be performed using broadcasting
# Shapes (1,3) and (3,4) Broadcasting Will not work

#If x=b=1 and y=b the boroadcasting will work and the result will be of shape (y,b)
#Scenario 4
a6 = np.arange(3).reshape(1,3)
a7 = np.arange(3).reshape(3,1)

print(a6, "\n")
print(a7, "\n")
print(a6+a7)

[[0 1 2]] 

[[0]
 [1]
 [2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [19]:
# If x=y=1 and a and b are any number then that one element will get boradcasted to the shape (a,b)
# Basically they are of different dimentions
#Scenario 5
a8 = np.array([3])
a9 = np.arange(56).reshape(7,8)

print(a8, "\n")
print(a9, "\n")

print(a8+a9)

[3] 

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]] 

[[ 3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58]]
