### Some Important NumPy Functions

In [1]:
import numpy as np

**Random Module**

In [46]:
np.random.random() # any random value between 0 and 1
# This changes everytime we run it

0.7203244934421581

In [47]:
# Setting a seed so that new random does not get generated on every run
np.random.seed(1) # 1 is any constant
np.random.random() # Now it will give the same number all the time

0.417022004702574

In [127]:
#Single random number within a range
np.random.uniform(30,40) 

39.49489258707071

In [153]:
# Number of random numbers within a range
np.random.uniform(30,40,12).reshape(4,3) #Array of 10 random numbers within range (30,40)

array([[36.69232893, 32.64919558, 30.66334834],
       [33.70084198, 36.29717507, 32.1017401 ],
       [37.52755554, 30.66536481, 32.60315099],
       [38.04754564, 31.93434283, 36.39460881]])

In [163]:
#For integers within a range
np.random.randint(30,40,12).reshape(4,3) # Same as above with just integers

array([[30, 34, 37],
       [33, 30, 31],
       [36, 30, 36],
       [31, 36, 34]])

**min, max, argmin, argmax**

In [168]:
arr1 = np.random.randint(0,100,12).reshape(4,3)
print(arr1, "\n")

print(np.max(arr1)) # Maximum
print(np.min(arr1)) # Minimum
print(np.argmax(arr1)) # Index of Maximum
print(np.argmin(arr1)) # Index of Minimum

[[ 4 88 27]
 [50 68  3]
 [58 12  2]
 [76 96 96]] 

96
2
10
8


In [173]:
# Example- Raplace all the odd digits by -1
arr2 = np.random.randint(0,100,15).reshape(5,3)
print(arr2)

arr2[arr2%2!=0] = -1 # This replaces the original array
print(arr2)

[[27 51 77]
 [30 43 46]
 [ 9 67  3]
 [67 54 97]
 [63 99 80]]
[[-1 -1 -1]
 [30 -1 46]
 [-1 -1 -1]
 [-1 54 -1]
 [-1 -1 80]]


**Where**

In [179]:
#Example replace with -1 but create a new array
arr2 = np.random.randint(0,100,15).reshape(5,3)
print(arr2)

out_arr = np.where(arr2%2!=0, -1, arr2) # parameter 1: condition, 2: replace with, 3: replace when condition fails

print(out_arr)
print(arr2) # Remains same

[[15 51 98]
 [86 45 63]
 [42 22 82]
 [40 44 16]
 [17 88  0]]
[[-1 -1 98]
 [86 -1 -1]
 [42 22 82]
 [40 44 16]
 [-1 88  0]]
[[15 51 98]
 [86 45 63]
 [42 22 82]
 [40 44 16]
 [17 88  0]]


**Percentile (25, 50, 75)**

In [190]:
arr3 = np.random.randint(0,100,100)
print(arr3, "\n")
arr3 = np.sort(arr3) # First Sorting the Array
print(arr3, "\n")

print("25% of the values are below: ", np.percentile(arr3,25), "\n")
print("50% of the values are below: ", np.percentile(arr3,50), "\n")
print("75% of the values are below: ", np.percentile(arr3,75), "\n")

[87 77 62 48  0 42 39  3 57 43 53 43 74 98 97 75 59 66 74 91  5 26 67 31
 11  3 54  1 13 59 56 81  8 38  4 70 76 73  5 79 84 59 31 90  7 66 32 46
 75 82 44 64 37 47 73 90 84 15 65 52 69 66 89 28 19 17  5 79 10 29 17 81
 46  7 17 86 61 64  7 29 55 28 99 43 98 55  5 50 92 63 52 34 98 83 77 37
 89 54  4 43] 

[ 0  1  3  3  4  4  5  5  5  5  7  7  7  8 10 11 13 15 17 17 17 19 26 28
 28 29 29 31 31 32 34 37 37 38 39 42 43 43 43 43 44 46 46 47 48 50 52 52
 53 54 54 55 55 56 57 59 59 59 61 62 63 64 64 65 66 66 66 67 69 70 73 73
 74 74 75 75 76 77 77 79 79 81 81 82 83 84 84 86 87 89 89 90 90 91 92 97
 98 98 98 99] 

25% of the values are below:  28.75 

50% of the values are below:  54.0 

75% of the values are below:  75.0 

